### ISSUE TITLE
Can U2C module not connecting to SB2240

### ISSUE THREAD

**Issue by CircuitR** [bigtreetech/BTT-Pi#17]
Hi, I have followed the manual for the SB2240, but when I try to flash the SB2240 via Can I get flash error

ERROR:root:Flash Error
Traceback (most recent call last):
  File "/home/biqu/CanBoot/scripts/flash_can.py", line 493, in run_query
    self.cansock.bind((intf,))
OSError: [Errno 19] No such device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/biqu/CanBoot/scripts/flash_can.py", line 621, in main
    loop.run_until_complete(sock.run_query(intf))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/biqu/CanBoot/scripts/flash_can.py", line 495, in run_query
    raise FlashCanError("Unable to bind socket to can0")
FlashCanError: Unable to bind socket to can0

Please advise to fix.

**Comment by Rivega42** [comment]
Did you manage to fix it?
